name: phuc
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pyyaml
  - rospkg
  - catkin_pkg
  - pip:
      - numpy==2.2.6
      - opencv-contrib-python==4.13.0.92
      - pillow
      - matplotlib
